import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowUpRight, CalendarDays, ChevronRight, CircleAlert, ClipboardCheck, Clock3, FilePlus2, HeartPulse, Plus, ShieldAlert, Sparkles, UserRoundPlus, Users, UsersRound } from 'lucide-react'
import { careApi } from '../lib/api'
import { Avatar, PageHeader, Pill, RiskPill } from '../components/Layout'
import { Button, EmptyState, StatCard } from '../components/ui'
import { useLanguage } from '../i18n'

const stagger = { hidden: { opacity: 0, y: 12 }, show: { opacity: 1, y: 0, transition: { duration: .35 } } }

export default function Dashboard({ user }) {
  const { t } = useLanguage()
  const demo = false
  const [visibleMothers, setVisibleMothers] = useState([])
  const visibleActivity = []
  useEffect(() => { careApi.mothers().then(({ data }) => setVisibleMothers((data.mothers || []).map((item) => ({ id: String(item.id), name: item.full_name, gestationalWeeks: item.weeks_pregnant || 0, risk: 'Low', initials: item.full_name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase(), color: 'teal' })))).catch(() => setVisibleMothers([])) }, [])
  const highRisk = visibleMothers.filter((mother) => mother.risk === 'High').length
  const hasData = visibleMothers.length > 0
  return <motion.div initial="hidden" animate="show" variants={{ show: { transition: { staggerChildren: .06 } } }}>
    <PageHeader eyebrow={t('dashboard.eyebrow')} title={t('dashboard.greeting', 'Good morning, {firstName}', { firstName: user.firstName })} description={t('dashboard.description')} actions={<Link to="/visits/new"><Button icon={Plus}>{t('dashboard.recordVisit')}</Button></Link>} />
    <motion.div variants={stagger} className="dashboard-banner"><div className="banner-icon"><HeartPulse size={22} /></div><div><strong>{hasData ? t('dashboard.bannerTitle') : 'Your workspace is ready.'}</strong><span>{hasData ? t('dashboard.bannerText', 'You have {count} high-risk pregnancy that needs attention today.', { count: highRisk }) : 'Register your first mother to start building your care list.'}</span></div>{hasData && <Link to="/mothers/m-1">{t('dashboard.reviewAlert')} <ArrowUpRight size={15} /></Link>}</motion.div>
    <motion.div variants={stagger} className="stats-grid"><StatCard label={t('dashboard.totalMothers')} value={visibleMothers.length} note={demo ? '+3 this month' : 'No records yet'} icon={UsersRound} tone="blue" trend={demo ? '+14%' : undefined} /><StatCard label={t('dashboard.highRisk')} value={highRisk} note={hasData ? 'Needs your attention' : 'No records yet'} icon={ShieldAlert} tone="red" /><StatCard label={t('dashboard.upcomingVisits')} value={demo ? '8' : '0'} note={demo ? 'In the next 7 days' : 'No visits scheduled'} icon={CalendarDays} tone="amber" trend={demo ? '+2' : undefined} /><StatCard label={t('dashboard.visitsToday')} value={demo ? '3' : '0'} note={demo ? '1 remaining' : 'No visits today'} icon={ClipboardCheck} tone="green" /><StatCard label={t('dashboard.aiAssessments')} value={demo ? '87' : '0'} note={demo ? 'This month' : 'No assessments yet'} icon={Sparkles} tone="purple" trend={demo ? '+24%' : undefined} /></motion.div>
    <div className="dashboard-grid">
      <motion.section variants={stagger} className="panel activity-panel"><div className="panel-header"><div><h2>{t('dashboard.recentActivity')}</h2><p>{t('dashboard.activityDescription')}</p></div><Link className="panel-link" to="/visits">{t('dashboard.viewAll')} <ChevronRight size={15} /></Link></div>{visibleActivity.length ? <div className="activity-list">{visibleActivity.map((item) => <div className="activity-row" key={item.title}><div className={`activity-icon activity-${item.tone}`}>{item.icon === 'alert' ? <CircleAlert size={17} /> : item.icon === 'check' ? <ClipboardCheck size={17} /> : <UserRoundPlus size={17} />}</div><div className="activity-copy"><strong>{item.title}</strong><span>{item.text}</span></div><time>{item.time}</time></div>)}</div> : <EmptyState icon={Users} title="No activity yet" description="New registrations and visits will appear here." />}<div className="activity-footer">{demo ? <><div className="avatar-stack"><Avatar initials="AN" color="coral" /><Avatar initials="RN" color="lilac" /><Avatar initials="HK" color="mint" /><span>+21</span></div><span>24 mothers in your care list</span></> : <span>No mothers have been added yet.</span>}</div></motion.section>
      <motion.section variants={stagger} className="panel followups-panel"><div className="panel-header"><div><h2>{t('dashboard.upcomingFollowups')}</h2><p>{t('dashboard.followupsDescription')}</p></div><Link className="panel-link" to="/mothers">{t('dashboard.seeCalendar')} <ChevronRight size={15} /></Link></div>{demo ? <div className="followup-list"><FollowUp mother={visibleMothers[0]} date="Today" time="10:30 AM" tone="red" /><FollowUp mother={visibleMothers[4]} date="Fri, 22 Aug" time="9:00 AM" tone="amber" /><FollowUp mother={visibleMothers[1]} date="Tue, 26 Aug" time="2:00 PM" tone="blue" /></div> : <EmptyState icon={CalendarDays} title="No upcoming follow-ups" description="Follow-ups will appear after you record visits." />}<Link to="/visits/new" className="dashed-action"><Plus size={16} /> Schedule a follow-up</Link></motion.section>
      <motion.section variants={stagger} className="panel risk-panel"><div className="panel-header"><div><h2>{t('dashboard.highRiskAlerts')}</h2><p>{t('dashboard.highRiskDescription')}</p></div>{highRisk > 0 && <Pill tone="danger" dot>{highRisk} active</Pill>}</div>{highRisk > 0 ? <><div className="risk-alert-card"><div className="risk-alert-top"><div className="risk-alert-avatar"><CircleAlert size={18} /></div><div><strong>Amina Nakato</strong><span>Assessed 02 Aug · 32 weeks</span></div><RiskPill level="High" /></div><div className="risk-alert-reason"><strong>Possible gestational hypertension</strong><span>BP 148/94 mmHg · Headache · Swollen feet</span></div><div className="risk-alert-actions"><Link to="/mothers/m-1">View profile <ChevronRight size={15} /></Link><button><PhoneIcon /> Call supervisor</button></div></div><div className="risk-note"><CircleAlert size={15} /><span>1 mother needs a referral follow-up this week.</span><Link to="/visits">Review</Link></div></> : <EmptyState icon={ShieldAlert} title="No high-risk alerts" description="Safety alerts will appear after a visit is assessed." />}</motion.section>
      <motion.section variants={stagger} className="panel quick-panel"><div className="panel-header"><div><h2>{t('dashboard.quickActions')}</h2><p>{t('dashboard.quickActionsDescription')}</p></div></div><div className="quick-actions"><Link to="/mothers/new" className="quick-action"><div className="quick-icon quick-blue"><UserRoundPlus size={19} /></div><span><strong>{t('dashboard.registerMother')}</strong><small>{t('dashboard.registerMotherDescription')}</small></span><ChevronRight size={16} /></Link><Link to="/visits/new" className="quick-action"><div className="quick-icon quick-green"><FilePlus2 size={19} /></div><span><strong>{t('dashboard.recordVisit')}</strong><small>Capture vitals and observations</small></span><ChevronRight size={16} /></Link><Link to="/assistant" className="quick-action"><div className="quick-icon quick-purple"><Sparkles size={19} /></div><span><strong>{t('dashboard.askCopilot')}</strong><small>{t('dashboard.askCopilotDescription')}</small></span><ChevronRight size={16} /></Link></div></motion.section>
    </div>
  </motion.div>
}

function FollowUp({ mother, date, time, tone }) {
  return <div className="followup-row"><Avatar initials={mother.initials} color={mother.color} /><div className="followup-copy"><strong>{mother.name}</strong><span>{mother.gestationalWeeks} weeks · {mother.risk} risk</span></div><div className={`followup-date followup-${tone}`}><strong>{date}</strong><span><Clock3 size={12} />{time}</span></div></div>
}

function PhoneIcon() { return <span className="phone-icon">☎</span> }
